services:
  symfony:
    build: ./
    # restart: always
    user: "1000:1000"
    ports:
      - 80:80
    depends_on:
      - db
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/more_upload_size.ini
      - ../../:/var/www/html
  db:
    image: mariadb:11.4.4
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2.2-apache
    # restart: always
    depends_on:
      - db
    ports:
      - 8000:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
